repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: fmt
        name: cargo fmt
        entry: cargo fmt --all -- --check
        language: system
        pass_filenames: false
        types: [rust]

      - id: clippy
        name: clippy (host)
        entry: cargo clippy -- -D warnings
        language: system
        pass_filenames: false
        types: [rust]

      - id: check
        name: check (host)
        entry: cargo check
        language: system
        pass_filenames: false
        types: [rust]

      - id: clippy-firmware
        name: clippy (firmware)
        entry: cargo clippy-fw -- -D warnings
        language: system
        pass_filenames: false
        types: [rust]

      - id: check-firmware
        name: cargo check (firmware)
        entry: cargo check-fw
        language: system
        pass_filenames: false
        types: [rust]
