[target.thumbv7em-none-eabihf]
runner = 'probe-rs run --chip STM32F407VGTx'
rustflags = [
    "-C", "link-arg=--nmagic",
    "-C", "link-arg=-Tlink.x",
]

[build]
target = "thumbv7em-none-eabihf"

[env]
DEFMT_LOG = "info"

[unstable]
build-std = ["core"]
build-std-features = ["panic_immediate_abort"]

[alias]
host-test = "test --package pedalbox_lib --target x86_64-unknown-linux-gnu --no-default-features --lib"
host-build = "build --package pedalbox_lib --target x86_64-unknown-linux-gnu --no-default-features --lib"
host-clippy = "clippy --package pedalbox_lib --target x86_64-unknown-linux-gnu --no-default-features --lib"
