[target.thumbv7em-none-eabihf]
runner = 'probe-rs run --chip STM32F407VGTx'
rustflags = [
    "-C", "link-arg=--nmagic",
    "-C", "link-arg=-Tlink.x",
]

[env]
DEFMT_LOG = "info"

[alias]
check-fw = "check -p firmware -p defmt-embassy-usbserial --target thumbv7em-none-eabihf"
build-fw = "build -p firmware --target thumbv7em-none-eabihf"
flash = "run -p firmware --target thumbv7em-none-eabihf"
clippy-fw = "clippy -p firmware -p defmt-embassy-usbserial --target thumbv7em-none-eabihf"
